config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :issues do
    member do
      patch :execute
    end
    collection do
      post :clear_all
    end
  end

  resources :jira_sessions, only: [:new, :create] do
    collection do
      delete :destroy
    end
  end

  get "/builds/:id", to: "builds#analyze", as: "builds"
  root to: "issues#index"
end

app/models/issue.rb
class Issue < ApplicationRecord
  after_initialize :init_vars
  before_save :parse_lines

  scope :for, -> (jira_username) {
    where(jira_username: jira_username)
  }

  validates_presence_of :jira_username

  def <<(line)
    @lines << line.gsub(/\e\[[0-9]+m/,"").strip
  end

  def reparse!
    self.title = nil
    parse_lines
    save!
  end

  def extra_info=(info)
    @lines << info[:start_time].presence
    @lines << info[:ruby].presence
    @lines << info[:rails].presence
    @lines.compact!
    @lines << ""
  end

  def description
    self.trace
  end

  protected
  def init_vars
    @test_regexp = Regexp.new("(@ |^)(test/.*.rb):(\\d+):")
    @lines = []
  end

  def parse_lines
    self.trace = @lines.join("\n") if @lines.present?
    self.trace.split("\n").each do |line|
      if m = @test_regexp.match(line) #test/integration/applicants_old_checks_test.rb:307:
        # puts "\e[32m" + "m[1]=#{(m[1]).inspect}" + "\e[39m"
        self.title ||= "#{m[2]}:#{"%04d" % [m[3]]}"
        break
      end
    end
  end
end

app/controllers/issues_controller.rb
require "travis_log_parser"
require 'open-uri'


class IssuesController < ApplicationController
  before_action :verify_jira_session
  helper_method :matching_jira_issues

  def index
    @issues = Issue.for(jira_username).order(created_at: :desc)
  end

  def new
  end

  def create
    log_text = nil
    if build_number = params[:travis_log][:build_number].presence
      matched_build_number = build_number.match(/(\d+)/)
      redirect_to builds_path(id: matched_build_number[1])
    else
      if url = params[:travis_log][:url].presence
        open(url) do |f|
          log_text = f.read
        end
      end
      if params[:travis_log][:text].presence
        log_text = params[:travis_log][:text]
      end
      if log_text.present?
        tests, report = TravisLogParser.new(log_text, jira_username).tests
        if tests.size == report
          flash[:notice] = "#{tests.size} new issues found."
        else
          flash[:alert] = "#{tests.size} new issues found, but #{report-tests.size} couldn't be parsed."
        end
      else
        flash[:alert] = "No log to parse!"
      end

      redirect_to issues_path
    end
  end

  def edit
    @issue = Issue.find(params[:id])
  end

  def update
    @issue = Issue.find(params[:id])
    if @issue.update_attributes(issue_params)
      flash[:notice] = "Issue saved"
      redirect_to root_path
    else
      flash[:alert] = "An error occured! Try again."
      render :edit
    end
  end

  def execute
    @issue = Issue.find(params[:id])
    case issue_params[:action]
      when "new"
        @jira.create_issue(@issue)
      when "destroy"
        # Destroying @issue below
      else
        @jira.reopen_and_comment_on_issue(issue_params[:action], @issue)
    end

    @issue.destroy
    respond_to do |format|
      format.js
      format.json { render json: "OK", status: :success }
    end
  end

  def clear_all
    Issue.for(jira_username).destroy_all
    flash[:notice] = "All issues removed!"
    redirect_to root_path
  end

  protected
  def jira_issues
    @_jira_issues = []
    if @_jira_issues.empty?
      @jira.issues.each do |i|
        @_jira_issues << {
          key: i.key,
          summary: i.summary,
          status: i.status.name,
          resolution: i.resolution.try(:[], "name"),
          assignee: i.assignee.try(:displayName)
        }
      end
    end
    @_jira_issues
  end

  def matching_jira_issues(issue)
    threshold = 10
    distances = {}
    jira_issues.each do |i|
      distances[i] = [
        Vladlev.distance(issue.title, i[:summary], threshold),
        Vladlev.distance("Build failure: #{issue.title}", i[:summary], threshold),
        Vladlev.distance("#{File.basename(issue.title.to_s, File.extname(issue.title.to_s))}", i[:summary], threshold)
      ].min
    end
    distances.select { |i,d| d < threshold }.sort_by(&:last)
  end

  def issue_params
    params.require(:issue).permit(:title, :trace, :action)
  end


  # user     system      total        real

    # https://github.com/GlobalNamesArchitecture/damerau-levenshtein
    # DamerauLevenshtein.distance(i.title, j[:summary])
    # DamerauLevenshtein:    0.100000   0.010000   0.110000 (  0.106576)

    # https://github.com/dbalatero/levenshtein-ffi
    # Levenshtein.distance(i.title, j[:summary])
    # Levenshtein:          12.050000   0.120000  12.170000 ( 12.274638)

    # https://github.com/tliff/levenshtein
    # Levenshtein.distance(i.title, j[:summary])
    # levenshtein-ffi:       0.080000   0.000000   0.080000 (  0.076309)

    # https://github.com/mxenabled/vladlev
    # Vladlev.distance(i.title, j[:summary])
    # Vladlev:               0.070000   0.000000   0.070000 (  0.071638)
end

app/views/issues/_instructions.html.erb
<% help(:instruction) do %>
    <div class="well">
      <h3>Instructions</h3>
      <p>
        The goal of this project is to update the <%= link_to("'#{@jira_epic_text}'", @jira_epic_url, target: "_blank") %>
        Epic in JIRA with recurring test failure. It parses Travis log, extract failing tests and allows you to take action on them.
      </p>

      <p>With this interface, you can:</p>
      <ul>
        <li><b>Open a new JIRA</b> ticket linked to the <%= "'#{@jira_epic_text}'" %> Epic for a newly recurring test.</li>
        <li><b>Update an existing JIRA</b> ticket by adding a comment to it. This helps identify tests that
          are failling more frequently</li>
        <li><b>Reopen a closed JIRA</b> ticket. Save things as update, but also reopen the ticket if it was closed.</li>
        <li><b>Remove it from this list</b>. For when a test is failing because of you. Does nothing!</li>
        <li><b>Upload a Travis log</b> manually (top right)</li>
      </ul>

      <p>Please be aware that these JIRA will not fix themself. So when you have time, pick one and fix it.</p>
      <p>The team will thank you!</p>
    </div>
<% end %>

app/views/issues/_manual_upload.html.erb
<% help(:manual_upload) do %>
    <div class="well">
      <h3>Manual upload</h3>
      <p>
        If you wish to manually upload a Travis log.
      </p>

      <p>You have 3 options:</p>
      <ul>
        <li><b>Travis Build number</b> Written at the top of your build page.</li>
        <li><b>URL of a raw Travis log</b> Link to the raw log is located in the upper right corner of the blank log section in a job page.</li>
        <li><b>Raw Travis log text</b> Same as above, except you cut and paste the entire log</li>
      </ul>
    </div>
<% end %>

app/views/issues/edit.html.erb
<%= form_with(model: @issue, local: true) do |form| %>
    <div class="field form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :trace %>
      <%= form.text_area :trace,  rows: 15, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit "Save", class: "btn btn-default" %>
      <%= link_to 'Back', root_path, class: "btn btn-info" %>
    </div>
<% end %>

app/views/issues/index.html.erb
<% content_for :header do %>
    Recurring Failing tests
<% end %>

<div class="row">
  <div class="col-md-12">
    <%= link_to "Upload Travis log", new_issue_path, class: "btn btn-default pull-right" %>
    <%= link_to "Clear all", clear_all_issues_path, class: "btn btn-default pull-right", method: :post %>
  </div>
</div>

<div class="row">
  &nbsp;
</div>

<%= render "instructions" %>

<div class="row">
  <% if @issues.empty? %>
      <div class="alert alert-info">
        No issue found!
      </div>
  <% else %>
      <% @issues.each do |issue| %>

          <div id="issue_<%= issue.id %>" class="issue panel panel-default">
            <div class="panel-heading">
              <%= link_to "Edit", edit_issue_path(issue), class: "pull-right" %>
              <strong><%= issue.title %></strong>
            </div>
            <div class="panel-body">
              <pre class="pre-scrollable"><%= issue.description %></pre>
            </div>
            <div class="panel-body">
              <%= form_with(model: issue, url: execute_issue_path(issue)) do |form| %>
                  <div class="field">

                    <% matching_jira_issues(issue).each do |jira_issue, levenshtein_distance| %>
                        <%= issue_radio_button(form, jira_issue, levenshtein_distance) %><br>
                    <% end %>

                    <%= label_tag do %>
                        <%= form.radio_button :action, :new %>
                        Create a new JIRA.
                    <% end %><br>

                    <%= label_tag do %>
                        <%= form.radio_button :action, :destroy, checked: true %>
                        This is not a failed test. Remove it from this list.
                    <% end %><br>
                  </div>

                  <div class="actions">
                    <%= form.submit "Execute", data: { "disable-with": "Executing..." } %>
                  </div>
              <% end %>
            </div>
          </div>
      <% end %>
  <% end %>
</div>


<% if params[:issue_debug].present? %>
    <% @jira.issues.each_with_index do |i, idx| %>
        <%= link_to i.key, "?issue_debug=#{idx}" %>
    <% end %>

    <pre>
      <%= @jira.issues[params[:issue_debug].to_i].status %>
    </pre>

    <pre>
      <%= @jira.issues[params[:issue_debug].to_i].to_yaml %>
    </pre>
<% end %>

app/views/issues/new.html.erb
<h1>Cut and paste Travis log</h1>

<%= render "manual_upload" %>

<%= form_with(scope: :travis_log, url: issues_path, method: :post, local: true) do |form| %>
    <div class="field form-group">
      <%= form.label :url, "Travis Build number:" %>
      <%= form.text_field :build_number, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :url, "URL of a raw Travis log:" %>
      <%= form.text_field :url, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :text, "Raw Travis log text:" %>
      <%= form.text_area :text,  rows: 15, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit "Parse Log", class: "btn btn-success" %>
      <%= link_to 'Back', root_path, class: "btn btn-info" %>
    </div>
<% end %>