config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :issues do
    member do
      patch :execute
    end
    collection do
      post :clear_all
    end
  end

  resources :jira_sessions, only: [:new, :create] do
    collection do
      delete :destroy
    end
  end

  get "/builds/:id", to: "builds#analyze", as: "builds"
  root to: "issues#index"
end

app/controllers/jira_sessions_controller.rb
class JiraSessionsController < ApplicationController
  skip_before_action :verify_jira_session

  # GET /jira_sessions/new
  def new
  end

  # POST /jira_sessions
  # POST /jira_sessions.json
  def create
    session[:jira_username] = params[:jira_session][:username]
    session[:jira_password] = params[:jira_session][:password]
    if session[:build_number].present?
      build_number = session[:build_number]
      session[:build_id] = nil
      redirect_to builds_path(id: build_number)
    else
      redirect_to root_path, notice: "Logged in!"
    end
  end

  # DELETE /jira_sessions/1
  # DELETE /jira_sessions/1.json
  def destroy
    reset_session
    redirect_to root_path, notice: "Logged out!"
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def jira_session_params
      params.require(:jira_session).permit(:username, :password)
    end
end

app/views/jira_sessions/_form.html.erb
<%= form_with(scope: :jira_session, url: jira_sessions_path, method: :post, local: true) do |form| %>
    <div class="field form-group">
      <%= form.label :username, "Username / Email" %>
      <%= form.text_field :username, id: :jira_session_username, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :password %>
      <%= form.password_field :password, id: :jira_session_password, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit "Login", class: "btn btn-default" %>
    </div>
<% end %>

app/views/jira_sessions/new.html.erb
<% content_for :header do %>
    New Jira Session
<% end %>

<div class="well">
  <h3>Input your JIRA credentials.</h3>
  <p>
    They will be encrypted and recorded in your browser's session and used to identify you at <%= @jira_base_url %>.
  </p>
  <p>
    The goal of this project is to update the <%= link_to("'#{@jira_epic_text}'", @jira_epic_url, target: "_blank") %> Epic in JIRA with recurring test failure.
  </p>
</div>

<%= render 'form', jira_session: @jira_session %>